### ISSUE TITLE
Getting System.NotImplementedException exception

### ISSUE THREAD

**Issue by KLia** [snowflakedb/snowflake-connector-net#169]
I am trying to get some data into snowflake, and I am getting the following exception:

```System.NotImplementedException: The method or operation is not implemented.
   at Snowflake.Data.Core.SFDataConverter.csharpTypeValToSfTypeVal(DbType srcType, Object srcVal)
   at Snowflake.Data.Client.SnowflakeDbCommand.convertToBindList(List`1 parameters)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteInternal(Boolean describeOnly)
   at Snowflake.Data.Client.SnowflakeDbCommand.ExecuteNonQuery()
   at PaymentTransactionsToSnowflake.DbFunctions.SaveTransactionToDb(PaymentTransaction paymentTransaction) 
```

My sql statement looks like the following:
  ``` 
var insertCmd = $@"INSERT INTO Transactions ( 
   APPLICATION_REFERENCE,
   GAME_ID,
   ACTOR_ID)
VALUES (
   @appRef,
   @gameId,
   @actorId
)";
```

And then I try to bind the parameter values:

```
private static void AddParameter(IDbCommand cmd, string paramName, object paramValue)
       {
             var parameter = cmd.CreateParameter();
             parameter.ParameterName = paramName;
             parameter.Value = paramValue;

             cmd.Parameters.Add(parameter);
       } 
```

I might be doing the whole parameter binding wrong, but the exception itself isn't very insightful. Could you point me to the right direction?

Thanks.

**Comment by KLia** [comment]
I think I got it to work by converting the params into `(?)` and adding a DbType to each binding. I am still having an issue when binding ARRAY type. There are no DbType.Array type, so I am using a DbType.Object. This gives me the same exception as above, though

**Comment by ChTimTsubasa** [comment]
So far we cannot bind an array. This is a known limitation.
Our SQL support [Variant](https://docs.snowflake.net/manuals/sql-reference/data-types-semistructured.html#variant), but so far binding a variant is not supported yet.

**Comment by alexrosenfeld10** [comment]
@ChTimTsubasa @sfc-gh-stakeda it's been almost two years since this issue was addressed, is there any update on supporting `variant` types natively in the connector?

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for submitting this issue, and apologies for the long comment-less period. Now the server-side should support both datatypes I think, so we'll take a look how it could be implemented into the .NET client as well.

**Comment by brvndon-do** [comment]
> hello and thank you for submitting this issue, and apologies for the long comment-less period. Now the server-side should support both datatypes I think, so we'll take a look how it could be implemented into the .NET client as well.

so it's currently not implemented in the .NET client? I'm still having issues of `Bind variable ? not set` when attempting to bind an array in a parameter

**Comment by moravas** [comment]
Hi there!

Do you have any progress / any ETA regarding to this issue? This would be a very usefully feature in many cases, like IN clause, or SELECT in subqueries, etc

Thank you

**Comment by xujiabean** [comment]
any update on this feature

**Comment by sfc-gh-dszmolka** [comment]
hi @xujiabean can you please confirm what exactly you're trying to do and what is the error you're getting ? is it perhaps [Binding an array As Variable](https://github.com/snowflakedb/snowflake-connector-net/blob/master/doc/QueryingData.md#binding-an-array-as-variable) ?
